[project]
name = "ragnarok-core"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Xingkun", email = "18646154381@163.com" }
]
requires-python = ">=3.11"
dependencies = [
    "ragnarok-toolkit"
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
