[project]
name = "ragnarok-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Xingkun Fan", email = "18646154381@163.com" }
]
requires-python = ">=3.11"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "ragnarok-toolkit",
    "ragnarok-core",
    "sqlalchemy>=2.0.40",
    "alembic>=1.15.2",
    "asyncpg>=0.30.0",
    "greenlet>=3.1.1",
    "python-jose>=3.4.0",
    "passlib>=1.7.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
